package internal.pharmacy.system.project;

import java.util.ArrayList;
import java.util.List;

public class Manager extends Employee {

    private final List<Employee> employeesManaged;
    private final List<DistributingCompany> companiesManaged;

    public Manager(String employeeID, String name, String username, String password, String role) {
        super(employeeID, name, username, password, role);
        this.employeesManaged = new ArrayList<>();
        this.companiesManaged = new ArrayList<>();
    }
//----------------------------- getter -----------------------------------------
    public List<Employee> getEmployeesManaged() {
        return new ArrayList<>(employeesManaged);
    }

    public List<DistributingCompany> getCompaniesManaged() {
        return new ArrayList<>(companiesManaged);
    }
//------------------------------ method ----------------------------------------
    public void addEmployee(Employee emp) {
        if (emp == null) {
            System.out.println("Error: Cannot add a null employee.");
            return;
        }
        if (employeesManaged.contains(emp)) {
            System.out.println("Employee already exists in the system.");
            return;
        }
        employeesManaged.add(emp);
        System.out.println("Employee " + emp.getName() + " added successfully by Manager " + getName() + ".");
    }

    public void removeEmployee(String employeeID) {
        if (employeeID == null || employeeID.isBlank()) {
            System.out.println("Error: Invalid employee ID.");
            return;
        }
        Employee toRemove = null;
        for (Employee e : employeesManaged) {
            if (e.getEmployeeID().equalsIgnoreCase(employeeID)) {
                toRemove = e;
                break;
            }
        }
        if (toRemove != null) {
            employeesManaged.remove(toRemove);
            System.out.println("Employee " + toRemove.getName() + " removed successfully by Manager " + getName() + ".");
        } else {
            System.out.println("Error: Employee ID not found.");
        }
    }

    public void updateEmployeeCredentials(String employeeID, String newPassword) {
        if (employeeID == null || newPassword == null || newPassword.isBlank()) {
            System.out.println("Error: Invalid credentials input.");
            return;
        }
        for (Employee e : employeesManaged) {
            if (e.getEmployeeID().equalsIgnoreCase(employeeID)) {
                e.setPassword(newPassword);
                System.out.println("Password updated successfully for employee: " + e.getName());
                return;
            }
        }
        System.out.println("Error: Employee not found.");
    }

// --------------------- Company management ------------------------------------
    public void addCompany(DistributingCompany company) {
        if (company == null) {
            System.out.println("Error: Cannot add null company.");
            return;
        }
        for (DistributingCompany c : companiesManaged) {
            if (c.getCompanyID().equalsIgnoreCase(company.getCompanyID())) {
                System.out.println("Company already exists.");
                return;
            }
        }
        companiesManaged.add(company);
        System.out.println("Company " + company.getName() + " added.");
    }

    public void removeCompany(String companyID) {
        if (companyID == null || companyID.isBlank()) {
            System.out.println("Error: Invalid company ID.");
            return;
        }
        DistributingCompany toRemove = null;
        for (DistributingCompany c : companiesManaged) {
            if (c.getCompanyID().equalsIgnoreCase(companyID)) {
                toRemove = c;
                break;
            }
        }
        if (toRemove != null) {
            companiesManaged.remove(toRemove);
            System.out.println("Company " + toRemove.getName() + " removed.");
        } else {
            System.out.println("Company not found.");
        }
    }


    public void generateReport(String type) {
        if (type == null || type.isBlank()) {
            System.out.println("Error: Invalid report type.");
            return;
        }

        System.out.println("=== Report Generated by Manager " + getName() + " ===");
        switch (type.toLowerCase()) {
            case "sales":
                double totalSales = 0;
                System.out.println("=== Sales & Bonus Report ===");
                for (Employee e : employeesManaged) {
                    double bonus = e.calculateBonus(10); // 10% bonus
                    System.out.println("Bonus for " + e.getName() + ": " +Math.round(bonus));
                    totalSales += e.getTotalSales(); 
                }
                System.out.println("Total Sales from All Employees: " + totalSales);
                break;


            case "employees":
                System.out.println("Total Employees Managed: " + employeesManaged.size());
                for (Employee e : employeesManaged) {
                    System.out.println("- " + e.getName() + " (" + e.getRole() + ")");
                }
                break;

            case "suppliers":
            case "companies":
                System.out.println("Total Companies: " + companiesManaged.size());
                for (DistributingCompany c : companiesManaged) {
                    System.out.println(c.toString());
                    List<Product> prods = c.getSuppliedProducts();
                    if (prods.isEmpty()) {
                        System.out.println("  No products in catalog.");
                    } else {
                        System.out.println("  Products:");
                        for (Product p : prods) {
                            System.out.println("   - " + p.getName() + " (ID:" + p.getProductID() + ", Stock:" + p.getStockQuantity() + ")");
                        }
                    }
                }
                break;

            default:
                System.out.println("Unknown report type. Available: 'sales', 'employees', 'suppliers'.");
        }
    }

    @Override
    public void printSalesHistory() {
        System.out.println("Managers usually oversee others' sales, not personal ones.");
    }
}
